spring.application.name=loanrisk
spring.datasource.url=jdbc:postgresql://localhost:5432/loan_risk_db
spring.datasource.username=postgres
spring.datasource.password=Sql@123#456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect